### ISSUE TITLE
可以在dart自定义提示语吗

### ISSUE THREAD

**Issue by lan2000** [CodeGather/alarm_calendar#6]
比如安卓原生的提示：
Toast.makeText(context,"添加失败", Toast.LENGTH_SHORT).show();

提示语可以放到dart自己设置吗，自己设置的话还可以多语言适配

**Comment by lan2000** [comment]
你好，现在的timeZone固定为"Asia/Shanghai"
valueEvent.put(CalendarContract.Events.EVENT_TIMEZONE, "Asia/Shanghai");
为什么不设置为以下默认的呢。
valueEvent.put(CalendarContract.Events.EVENT_TIMEZONE, TimeZone.getDefault().getID());

**Comment by CodeGather** [comment]
提示语是可以在dart中自己处理的，插件没有做提示语
关于时间的问题待下一版本处理

**Comment by lan2000** [comment]
某些旧的手机出现以下错误：
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/icu/util/TimeZone;
&nbsp; &nbsp; &nbsp; &nbsp; at com.jokui.rao.alarm_calendar.CalendarProviderUtil.addEvent(CalendarProviderUtil.java:310)
&nbsp; &nbsp; &nbsp; &nbsp; at com.jokui.rao.alarm_calendar.AlarmCalendarPlugin.onMethodCall(AlarmCalendarPlugin.java:72)
&nbsp; &nbsp; &nbsp; &nbsp; at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
&nbsp; &nbsp; &nbsp; &nbsp; at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
&nbsp; &nbsp; &nbsp; &nbsp; at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.MessageQueue.nativePollOnce(Native Method)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.MessageQueue.next(MessageQueue.java:148)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Looper.loop(Looper.java:151)
&nbsp; &nbsp; &nbsp; &nbsp; at android.app.ActivityThread.main(ActivityThread.java:5904)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.reflect.Method.invoke(Native Method)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.reflect.Method.invoke(Method.java:372)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
&nbsp;&nbsp;

Caused by: java.lang.ClassNotFoundException: Didn't find class "android.icu.util.TimeZone" on path: DexPathList[[zip file "/data/app/com.xxx.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.debug-1/lib/arm, /vendor/lib, /system/lib]]
&nbsp; &nbsp; &nbsp; &nbsp; at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
&nbsp; &nbsp; &nbsp; &nbsp; at com.jokui.rao.alarm_calendar.CalendarProviderUtil.addEvent(CalendarProviderUtil.java:310)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at com.jokui.rao.alarm_calendar.AlarmCalendarPlugin.onMethodCall(AlarmCalendarPlugin.java:72)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.MessageQueue.nativePollOnce(Native Method)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.MessageQueue.next(MessageQueue.java:148)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Looper.loop(Looper.java:151)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at android.app.ActivityThread.main(ActivityThread.java:5904)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.reflect.Method.invoke(Native Method)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.reflect.Method.invoke(Method.java:372)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)&nbsp;
&nbsp; &nbsp; 	Suppressed: java.lang.ClassNotFoundException: android.icu.util.TimeZone
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Class.classForName(Native Method)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.ClassLoader.loadClass(ClassLoader.java:504)







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月29日(星期四) 上午9:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CodeGather/alarm_calendar] 可以在dart自定义提示语吗 (#6)





 
提示语是可以在dart中自己处理的，插件没有做提示语
 关于时间的问题待下一版本处理

**Comment by lan2000** [comment]
手机是 魅蓝m3s;
M3s (mobile); • Y15QFBNS23645; • android-arm64 • Android 5.1 (API 22)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (6 available)

某些手机报错，我直接运行demo也会这样：
  Process: com.jokui.rao.alarm_calendar_example, PID: 26541
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/icu/util/TimeZone;
        at com.jokui.rao.alarm_calendar.CalendarProviderUtil.addEvent(CalendarProviderUtil.java:310)
        at com.jokui.rao.alarm_calendar.AlarmCalendarPlugin.onMethodCall(AlarmCalendarPlugin.java:72)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:148)
        at android.os.Looper.loop(Looper.java:151)
        at android.app.ActivityThread.main(ActivityThread.java:5904)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.icu.util.TimeZone" on path: DexPathList[[zip file "/data/app/com.jokui.rao.alarm_calendar_example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.jokui.rao.alarm_calendar_example-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.jokui.rao.alarm_calendar.CalendarProviderUtil.addEvent(CalendarProviderUtil.java:310) 
        at com.jokui.rao.alarm_calendar.AlarmCalendarPlugin.onMethodCall(AlarmCalendarPlugin.java:72) 
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233) 
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85) 
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:148) 
        at android.os.Looper.loop(Looper.java:151) 
        at android.app.ActivityThread.main(ActivityThread.java:5904) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885) 
    	Suppressed: java.lang.ClassNotFoundException: android.icu.util.TimeZone
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

**Comment by CodeGather** [comment]
这个是时间不能这样设置
